### ISSUE TITLE
Control-M/Docker: Control-M/Enterprise Manager version 9.0.21.000 or newer is required for this operation

### ISSUE THREAD

**Issue by dilino118** [controlm/workbench#2]
I installed and started the dockerized Control-M/Enterprise Manager according to the instructions in https://hub.docker.com/r/controlm/workbench. When I use the provided Swagger-UI at https://localhost:8443/automation-api/swagger-ui.html, e.g. for an authentication token request, I get the following error: 

`
{
  "errors": [
    {
      "message": "Control-M/Enterprise Manager version 9.0.21.000 or newer is required for this operation"
    }
  ]
}
`

My request object: 
`
{ 
    "tokenName": "my-app-token",
    "expirationDate": "2023-02-20",
    "roles": ["admin","user"]
}
`

What did I overlook / do wrong? 

NOTE: All functions work via the CTM-CLI. 

Thanks in advance!

**Comment by ghost** [comment]
Hi,
The Control-M Workbench you were using was based on EM 9.20.200.
We just released a new version of the Control-M Workbench with EM 9.21.000 which should allow you to perform the operations with authentication service.
To download: docker pull controlm/workbench:latest or docker pull controlm/workbench:9.21.100

Thanks for the feedback!

**Comment by dilino118** [comment]
> Hi, The Control-M Workbench you were using was based on EM 9.20.200. We just released a new version of the Control-M Workbench with EM 9.21.000 which should allow you to perform the operations with authentication service. To download: docker pull controlm/workbench:latest or docker pull controlm/workbench:9.21.100
> 
> Thanks for the feedback!

Thanks a lot!
