### ISSUE TITLE
Lots of critical vulnerabilities...

### ISSUE THREAD

**Issue by daveshih01** [controlm/workbench#4]
Hello, are there plans to update the dependencies to help address/mitigate these critical vulnerabilities?
This is from the latest 9.21.105 tag of the image.
[ctm-workbench-vulnerabilities.txt](https://github.com/controlm/workbench/files/11103348/ctm-workbench-vulnerabilities.txt)

**Comment by ghost** [comment]
Hi,
Thanks for your comment and the provided list of issues.
The issues are reported for multiple components of Control-M and they are being addressed by each individual team for future releases of Control-M. Some of the issues may be solved already in the next couple of versions of Workbench and more should be solved in the future when we will update the base Control-M version.

**Comment by nathanw9722** [comment]
Closing as these are continuously delivered on.
